version: "3.9"
services:
  res-service:
    build: .
    image: pv207/service:v1
    restart: always
    volumes:
      - ./rest_service/rest_client:/backend/
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
  jbpm-service:
    image: jboss/jbpm-server-full:custom
    ports:
      - "8080:8080"
      - "8001:8001"
