# Generated by Django 4.0.4 on 2022-05-09 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('C', 'cleaning'), ('M', 'maintenance')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='incident',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='incident',
            name='state',
            field=models.CharField(choices=[('P', 'pending'), ('I', 'in_progress'), ('R', 'resolved'), ('D', 'declined')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('U', 'in_use'), ('S', 'in_service'), ('M', 'maintanance'), ('D', 'disabled')], default='D', max_length=1),
        ),
    ]
