# Generated by Django 4.0.4 on 2022-05-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_incident_type_incident_user_alter_incident_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('U', 'in_use'), ('I', 'idle'), ('S', 'in_service'), ('M', 'maintanance'), ('D', 'disabled')], default='D', max_length=1),
        ),
    ]
