# Generated by Django 4.0.4 on 2022-05-29 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_vehicle_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='location',
            field=models.CharField(default='49.208769, 16.595797', max_length=40),
        ),
    ]
