# Generated by Django 4.0.4 on 2022-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehicle_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='type',
            field=models.CharField(choices=[('C', 'cleaning'), ('M', 'malfunction')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='state',
            field=models.CharField(choices=[('U', 'in_use'), ('I', 'idle'), ('S', 'in_carservice'), ('C', 'in_carwash'), ('D', 'disabled')], default='D', max_length=1),
        ),
    ]
