# Generated by Django 4.0.4 on 2022-05-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_incident_type_alter_vehicle_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='resolution',
            field=models.CharField(default='', max_length=200),
        ),
    ]
